package it.unisi.dfclam.ela.debug;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import net.sf.json.JSONException;
import net.sf.json.JSONObject;
import net.sf.json.JsonConfig;
import net.sf.json.util.JsonEventListener;

public class DebugIssue21
{
	public static void main(String[] args) throws IOException
	{
		debugIssue21();
	}
	
	public static void debugIssue21() throws IOException
	{
		// Original file json file stored in ElasticSearch
//		final Path jsonFile = Path.of("/home/giulio/tmp/7caba5736b1d9e26c1a5a8af278a3383.json");
		
		// The CLTK part generated by the ELA TOOLS, and extracted with the tools/python/extract_cltk.py script
		final Path jsonFile = Path.of("/home/giulio/tmp/7caba5736b1d9e26c1a5a8af278a3383.cltk.json");
		final String jsonStr;
		try (Stream<String> stream = Files.lines(jsonFile))
		{
			jsonStr = stream.collect(Collectors.joining());
		}
		
		JsonConfig jsonConfig = new JsonConfig();
		jsonConfig.enableEventTriggering();
		jsonConfig.addJsonEventListener(new MyJsonEventListener());
		JSONObject jsonObject = JSONObject.fromObject(jsonStr, jsonConfig);
	}
	
	public static class MyJsonEventListener implements JsonEventListener
	{

		@Override
		public void onArrayEnd()
		{
			System.err.printf("onArrayEnd() - \n");
		}

		@Override
		public void onArrayStart()
		{
			System.err.printf("onArrayStart() - \n");
		}

		@Override
		public void onElementAdded(int index, Object element)
		{
			System.err.printf("onElementAdded(%d, %s) - \n", index, element);
		}

		@Override
		public void onError(JSONException jsone)
		{
			jsone.printStackTrace();
		}

		@Override
		public void onObjectEnd()
		{
			System.err.printf("onObjectEnd() - \n");
		}

		@Override
		public void onObjectStart()
		{
			System.err.printf("onObjectStart() - \n");
		}

		@Override
		public void onPropertySet(String key, Object value, boolean accumulated)
		{
			System.err.printf("onPropertySet(\"%s\", %s, %s) - \n", key, value, accumulated);
		}

		@Override
		public void onWarning(String warning)
		{
			System.err.printf("onWarning(\"%s\") - \n", warning);
		}
		
	}
}
